# crash area

In [6]:
%pylab inline
# %config InlineBackend.figure_format = 'retina'  # Use for retina display resolution

Populating the interactive namespace from numpy and matplotlib


In [2]:
import numpy as np
from rhavok.utils import mybuffer

In [6]:
bf = mybuffer(record_size = 5, dtype='|int8, bool, float64, float64, float64')
i = 0

In [7]:
bf.record( i, False, np.random.rand(3).round(1))
i += 1
bf.record( i, True, np.random.rand(3).round(2))
i += 1
bf.record( i, False, np.random.rand(3).round(2))
i += 1

(0, False, 0., 0., 0.)
[0.  0.  0.5 0.8 0.9]
(0, False, 0., 0., 0.)
[1.   1.   0.46 0.15 0.99]
(0, False, 0., 0., 0.)
[2.   0.   0.33 0.83 0.64]


In [8]:
k = bf.read_lifo(n=5)
k

array([(0, False, 0.5 , 0.8 , 0.9 ), (1,  True, 0.46, 0.15, 0.99),
       (2, False, 0.33, 0.83, 0.64)],
      dtype=[('f0', 'i1'), ('f1', '?'), ('f2', '<f8'), ('f3', '<f8'), ('f4', '<f8')])

In [14]:
k

array([(0, False, 0.5 , 0.8 , 0.9 ), (1,  True, 0.46, 0.15, 0.99),
       (2, False, 0.33, 0.83, 0.64)],
      dtype=[('f0', 'i1'), ('f1', '?'), ('f2', '<f8'), ('f3', '<f8'), ('f4', '<f8')])

NameError: name 'allo' is not defined

In [5]:
import matplotlib.pyplot as plt
plt.cm.magma(np.linspace(0,1,1000))

array([[1.46200e-03, 4.66000e-04, 1.38660e-02, 1.00000e+00],
       [1.46200e-03, 4.66000e-04, 1.38660e-02, 1.00000e+00],
       [1.46200e-03, 4.66000e-04, 1.38660e-02, 1.00000e+00],
       ...,
       [9.87053e-01, 9.91438e-01, 7.49504e-01, 1.00000e+00],
       [9.87053e-01, 9.91438e-01, 7.49504e-01, 1.00000e+00],
       [9.87053e-01, 9.91438e-01, 7.49504e-01, 1.00000e+00]])